[database]
database_host = localhost
database_name = airflow_OpenAq
database_port = 5432
database_username = postgres
database_password = postrgres

[file_paths]
input_path = /opt/airflow/data/input
output_path = /opt/airflow/data/output
[api_keys]
openaq_api_key = xxx
[openaq]
base_url = https://api.openaq.org/v3
locations_endpoint = /locations

[aws]
aws_access_key_id = xxx
aws_secret_access_key= xxxx
aws_region = us-east-1
aws_bucket_name = openap-air-quality

[etl_settings]
batch_size = 100
error_handling = abort
log_level = info